### ISSUE TITLE
Is not working for a class after babel transpile

### ISSUE THREAD

**Issue by alexlopez-natgeo** [miguelmota/is-class#7]
Works ok when is on a node-env but for my implementation on the browser the class is transpiled by babel and when I verify if `isClass` says is a function but then the browser says:

`Cannot call a class as a function`

**Comment by miguelmota** [comment]
@alexlopez-natgeo do you know the babel version?

**Comment by miguelmota** [comment]
Can't seem to reproduce. Here's the babel script to generate the transpiled code:

```js
var code = `class F {}`
var output = require('@babel/core').transform(code, {
  plugins: ['@babel/plugin-transform-classes']
})

console.log(output.code)
```

Here's is the transpiled code, which is being passed to `isClass`:

```js
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

let F = function F() {
  _classCallCheck(this, F);
};

var isClass = require('is-class')
console.log(isClass(F)) // true
```

Here's this same example in the browser

http://jsfiddle.net/xz7b5tqu/

Are you using the `@babel/plugin-transform-classes` plugin?

**Comment by nosferato** [comment]
Hi,
I'have the same issue when using babel (dev version). The thing is that there are some line breaks in string you check. It works as it should if you strip all the breaks. This is the line that works for me:
/^.*classCallCheck\(/.test(fnBody(fn).replace(/(\r\n|\n|\r)/gm, ""))

**Comment by nosferato** [comment]
I've looked into my code and regex and this is what is causing the issue
This is my text output:
```
"var _this = this;   
_classCallCheck(this, SomeClassName);  
 ...."
```
So it is transpiled with the new line. In regex pattern it says that classCallCheck must be on the first line ( the "^" inside /^.*classCallCheck\(/ ). Because of that it works when string is minified.

I assume that it is safe to remove "^" from the condition? Or maybe there is some other solution to this? @miguelmota 

Thanks in advance

**Comment by miguelmota** [comment]
@nosferato the latest release now has the `^.*` check removed. If you're still having problems please open an issue. Thanks!
